# config.yaml
proxy:
  secretToken: "4ee9d721336c4a5337c5bc15d9c7150c56c248656c0fef0fca5e4343447eba41" # You may need to change this token. Follow the instructions here: https://tanzu.vmware.com/developer/blog/data-science-with-python-jupyterhub-on-kubernetes-part-1/
singleuser:
  image:
    name: konsloiz/jupyter-kale
    tag: latest
  defaultUrl: "/lab"
  extraEnv:
    KF_PIPELINES_ENDPOINT: http://ml-pipeline-ui.kubeflow:80
