# config.yaml
proxy:
  secretToken: "4ee9d721336c4a5337c5bc15d9c7150c56c248656c0fef0fca5e4343447eba41"
singleuser:
  image:
    name: konsloiz/jupyter-kale
    tag: latest
  defaultUrl: "/lab"
  extraEnv:
    KF_PIPELINES_ENDPOINT: http://ml-pipeline-ui.kubeflow:80
    
hub:
  extraConfig: 
    ipaddress: |
     import os
     c.KubeSpawner.service_account = "hub"
